Adding Week 6 Blogpost
fury-gl/fury pull request #638
Opened 2022-07-21 16:34 UTC by ganimtron-10

Adding Weekly Blogpost.

![msedge_M5FpTfHo1P](https://user-images.githubusercontent.com/64432063/180266855-803956ad-6f9e-4543-b887-2ee7dec5386c.png)

2022-07-21 17:42 UTC, m-agour reviewed
Hi @ganimtron-10,
The name 'Week 6' makes me and @xtanion look so lazy :rofl:
Good job, there are no typos and it looks more like a blog post, mine looks more like a manifesto or something. 
Please see my suggestions below.

2022-07-21 17:43 UTC, m-agour commented on docs/source/posts/2022/2022-07-13-week-6-praneeth.rst
> +I improved the `polyline` feature by adding a separate class to manage the creation and manipulation of the lines but still, I was facing the same issue with the dragging event, which initialized a n
Maybe this better be `... the lines, but still; I was ...`

2022-07-21 17:43 UTC, m-agour commented on docs/source/posts/2022/2022-07-13-week-6-praneeth.rst
> +Rotation from the center wasn't working because the shape wasn't pivoted at the lower left corner due to which it was hard to calculate the center using it. To handle this I created an interface betw
Missing a comma after `To handle this`

2022-07-21 17:44 UTC, m-agour commented on docs/source/posts/2022/2022-07-13-week-6-praneeth.rst
> +Rotation from the center wasn't working because the shape wasn't pivoted at the lower left corner due to which it was hard to calculate the center using it. To handle this I created an interface betw
Missing comma after `bounding box`

2022-07-22 17:07 UTC, xtanion reviewed
Hi @ganimtron-10, Nice bog. There's no typos or grammatical errors, good job 👍🏽

2022-07-22 19:33 UTC, skoudoro requested changes
Hi @ganimtron-10,

Shorter are the sentences better and clearer it is.  Some of your sentences are really to understand. either, there are too long, or either you use `that` or `which` in a strange way.

Can you update some sentences? 

Thank you.

2022-07-22 19:33 UTC, skoudoro commented on docs/source/posts/2022/2022-07-13-week-6-praneeth.rst
> +Rotation from the center wasn't working because the shape wasn't pivoted at the lower left corner due to which it was hard to calculate the center using it. To handle this, I created an interface bet
> due to which it was hard to calculate the center using it

Not sure I understand, strange formulation.

2022-07-23 01:37 UTC, ganimtron-10 commented
Thank You @skoudoro for the review. 
I will consider these suggestions in my future blogs and try to improve them.

2022-07-26 16:35 UTC, ganimtron-10 commented
Hello @skoudoro ,
Is there anything else left on this PR??
I have updated the post according to the required changes.
PTAL.
Thanks!

2022-07-27 04:22 UTC, skoudoro approved these changes
No, all good, merging

2022-07-27 04:22 UTC, merged