Adding ability to load glTF animations
fury-gl/fury pull request #643
Opened 2022-07-25 16:28 UTC by xtanion

This PR adds the ability to load animation data from glTF files.

Check out this [example](https://github.com/xtanion/fury/blob/gltf-anim-merge-kf/docs/tutorials/01_introductory/viz_simple_gltf_animation.py) (merged with PR #626) to see the animation.

2022-07-25 17:43 UTC, m-agour commented
This looks so good! I tested the example and the animation is working. Great job.

2022-07-25 17:43 UTC, m-agour commented
Hello @xtanion ,
This looks so good! I tested the example and the animation is working. Great job.

2022-07-25 18:05 UTC, skoudoro commented
Thank you @xtanion. Please,  update the description and warn us that the status of this PR is still in work in progress. You still need to do many updates, add some tests, docstring, etc...

2022-07-27 08:47 UTC, pep8speaks commented
Hello @xtanion! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`fury/gltf.py`](https://github.com/fury-gl/fury/blob/df56c028ca747296eef9433986bb1e52e8abbd90/fury/gltf.py):

> [Line 25:15](https://github.com/fury-gl/fury/blob/df56c028ca747296eef9433986bb1e52e8abbd90/fury/gltf.py#L25): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-08-19 14:53 UTC, skoudoro requested changes
Hi @xtanion,

Can you commit your last changes here? 

Also, you need to rebase this PR, and fix the conflicts.

Thank you

2022-08-19 14:53 UTC, skoudoro commented on docs/tutorials/01_introductory/viz_gltf.py
> +fetch_gltf('CesiumMan', 'glTF')
you have to create a new tutorial. Do not use the same one

2022-09-08 14:30 UTC, skoudoro commented
Can you provide some feedback for this @xtanion? thank you

2022-09-08 18:05 UTC, xtanion commented
I'm cleaning the PR and documenting it. It shall be done by tomorrow.

2022-09-14 15:01 UTC, skoudoro reviewed
Can you add a test for `transform.py`?

Why some interpolators are in `gltf.py`? They should not be there. Can you update?

Thank you

2022-09-23 14:38 UTC, skoudoro reviewed
Hi @xtanion,

Can you also fix the typo for `apply_transfomation`. it is missing the `r`in transformation

2022-09-23 14:38 UTC, skoudoro commented on fury/gltf.py
> +            # We don't need this as we are already applying it in skinnning
comment or/and code to remove if we don't need this

2022-09-23 14:38 UTC, skoudoro commented on fury/gltf.py
> +            # print(matnode)
to remove

2022-09-23 14:38 UTC, skoudoro commented on fury/gltf.py
> +            # vertices = transform.apply_transfomation(vertices, transform_mat)
to remove

2022-09-23 14:38 UTC, skoudoro commented on fury/transform.py
> +def trs_from_matrix(transform):
missing docstring. to rename `transform_from_matrix`

2022-09-26 20:37 UTC, skoudoro commented
this PR needs still some work but I will go ahead and merge it. 

Can you add a test for `interpolator.py` in a new PR @xtanion. Thanks

2022-09-26 20:37 UTC, merged