[WIP] Cylindrical billboard implementation
fury-gl/fury pull request #677
Opened 2022-09-01 02:20 UTC by tvcastillod

The current billboard actor only supports spherical billboards functionality, this PR is intended to add the option of using cylindrical billboards.

2022-09-01 02:20 UTC, pep8speaks commented
Hello @tvcastillod! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fury/actor.py`](https://github.com/fury-gl/fury/blob/55e53b173e04179134a62c61a3334ce9543a3994/fury/actor.py):

> [Line 2352:1](https://github.com/fury-gl/fury/blob/55e53b173e04179134a62c61a3334ce9543a3994/fury/actor.py#L2352): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-09-12 16:27 UTC, guaje requested changes
@tvcastillod, thanks for this PR. Overall great job. Here are some comments:

2023-01-20 20:33 UTC, guaje requested changes
Besides the only comment on this review, I think this PR is ready to be merged.

2023-01-20 20:33 UTC, guaje commented on fury/tests/test_actors.py
> +def test_billboard_actor(interactive=True):
Change interactive to `false` so it doesn't freeze the main thread.

2023-03-03 00:04 UTC, tvcastillod commented
Hi @Garyfallidis, may you review this PR?

2023-03-03 16:35 UTC, skoudoro reviewed
Hi @tvcastillod,

Thank for this. Here, an initial review. I will go deeper a bit later:

- Concerning the shader file extension. it would be great if it is "*.frag" instead of "*.glsl"
- Also, it helps a lot if the filename ends by `_impl` or `_dec` to know if we just declare new function or update the core functionality
- It would be great to have a tutorial or update the billboard tutorial if it exists. Otherwise, it will not be used.

2023-03-03 16:35 UTC, skoudoro commented on fury/tests/test_actors.py
> +
Huge test for doing the exact same things.   Can you just create a small loop? thanks

2023-03-03 16:35 UTC, skoudoro commented on fury/actor.py
> +    bb_type : str
`str, optional` instead

2023-03-13 23:08 UTC, guaje requested changes
@tvcastillod, thanks for adding the requested changes. After a maintainers meeting, we agreed on changes related to adding shaders to Fury. The summary can be found in #753, and therefore the comments in this review are related to that.

2023-03-13 23:08 UTC, guaje commented on fury/actor.py
>          [import_fury_shader('billboard_dec.frag') + compose_shader(fs_dec)]
Please add the content of `billboard_dec.frag`  to the python implementation and remove the file to comply with #753. Additionally, replace `+` with `,` when using the `compose_shader` function.

2023-03-17 19:21 UTC, skoudoro reviewed
Hi @tvcastillod,

I suppose you made a mistake during your last commit named "solve conflict".  You merged the wrong version which create a mess. I recommend you to rebase this PR.

Currently, you are reverting many fixes.

Let us know if you need help

2023-03-18 00:01 UTC, guaje commented
@tvcastillod, thanks for rebasing and amending the PR to comply with #753. I don't have any more comments. @skoudoro what do you think?

2023-03-21 17:43 UTC, skoudoro approved these changes
All Good, Thank you for this work @tvcastillod, merging!

Now, Looking forward for an example of use!!

2023-03-21 17:43 UTC, merged