Record keyframe animation as GIF and MP4
fury-gl/fury pull request #687
Opened 2022-09-18 08:31 UTC by m-agour

This PR introduces a micro feature which is the ability to record the animation as GIF and MP4.

An example of GIF record:
![arm](https://user-images.githubusercontent.com/63170874/190892795-f47ceaf1-8dd0-4235-99be-2cf0aec323bb.gif)

MP4 Record:

https://user-images.githubusercontent.com/63170874/190893057-1cffac89-f560-4817-af53-df440e892537.mp4

2022-12-19 17:36 UTC, skoudoro requested changes
Hi @m-agour,

Let's tackle this PR! First, it needs to be rebased and conflicts needs to be fixed. 

Can you also remind me what else needs to be done in this PR?

Let me know when I can review it. Thanks

2022-12-19 17:36 UTC, skoudoro commented on fury/animation/tests/test_timeline.py
> +    scene.GetActiveCamera().SetPosition(0, 0, -100)
scene.set_camera(position=(0,0,-100))

2022-12-19 17:36 UTC, skoudoro commented on fury/animation/timeline.py
> +        order_transparent : bool
`, optional`

2023-01-30 22:03 UTC, skoudoro commented
Do you have an update on this @m-agour ?

2023-01-31 05:37 UTC, m-agour commented
@skoudoro I am working on it. Recording should be fast, but it currently takes more time than it should. I am working on speeding it up by minimizing or eliminating new VTK objects being created inside the recording loop.

2023-01-31 05:42 UTC, skoudoro commented
thank you for the feedback !

2023-03-02 16:40 UTC, Garyfallidis commented
self.window_to_image_filter.Modified()
self.window_to_image_filter.Update()

2023-03-17 16:17 UTC, skoudoro commented
Hi @m-agour,

Do you plan to do the update here? What is your timeline? Thank you for your feedback!

2023-04-06 03:54 UTC, skoudoro commented
ping @m-agour

2023-04-06 14:12 UTC, m-agour commented
@skoudoro Sorry for being behind schedule. I had some troubles trying to multi-thread the recording process. By tomorrow I would finish it and ping you

2023-04-07 20:54 UTC, m-agour commented
@skoudoro I modified the record method as we discussed by eliminating the creation of `WindowToImageFilter()` inside the rendering loop. Also eliminated all unnecessary loops except for the Rendering one. As for multi-threading but it has a lot of issues. So, I was thinking we could merge this and approach the multithreading option after.

2023-04-07 21:02 UTC, skoudoro commented
I agree for the multithreading approach in a new PR. 

I will test and review this PR a bit later today. thank you @m-agour !

2023-04-14 14:07 UTC, merged