Fix: Color changes on docs pages fixed
fury-gl/fury pull request #721
Opened 2023-01-09 15:34 UTC by Mk996

## Fix
- This PR fixes the font and footer color change in the documentation pages.

## Bug Details
- The bug got introduced due to the change of the version of the PyData theme over time. The code to configure the theme's colors was written in the style of `v0.8.1` but the current version getting used is, `v0.10.1`.

## Changes
- I have made changes in the `custom.css` file for defining the color scheme.
- I have made changes in the `sphinx-footer.css` file, originally the class applied to the footer from the theme was `.footer` but after the newer version, it started using the bootstrap, and the footer is getting the `.bd-footer` class applied from the theme.
- I have also removed all the error-creating imports, which were non-existent.
- I have fixed the hover issue on the fury logo text.
- I have introduced a common `navbar.css` file for a single source of truth of the navbar CSS and this file will grow as we will refractor all the hodgepodge code of the different CSS files.

## Backward Compatibility
- This PR will support the older version of the pyData theme.

2023-01-10 15:01 UTC, skoudoro requested changes
Hi @Mk996,

Thank you for this update.

- It is strange, but all the menu links from Homepage stopped to work. We cannot go to the installation page for example. I suppose, there is a conflict somewhere.
-  Also, see below: (The top right menu should be red and not black)
![image](https://user-images.githubusercontent.com/23106443/211585516-a42838cf-c9cb-4d95-b3d9-ba6c8d630387.png)

Apart from that, it looks good. 

Thanks

2023-01-11 18:10 UTC, Mk996 commented on docs/source/_static/css/navbar.css
> +/* Introducing a new css file for handling navbar css */
Introduced a new CSS file which will be the single source of truth for both `home.html`, `custom-title.html`, and `custom-navbar.html`.

This file will be expanded in the upcoming PR, I will shift the navbar CSS to this file

2023-01-11 18:11 UTC, Mk996 commented on docs/source/_static/vendor/new-promotions.css
> -@font-face {
Not used font faces and the files were also not present, causing errors in the console.

2023-01-11 18:12 UTC, Mk996 commented on docs/source/_static/vendor/styles.css
> -#navbar-item {
removed the duplicate id from navbar item and converted the CSS to follow the class

2023-01-11 18:13 UTC, Mk996 commented on docs/source/_templates/custom-footer.html
>                  <h5 class="footer-h5">About</h5>
formatted file

2023-01-11 18:13 UTC, Mk996 commented on docs/source/_templates/custom-navbar.html
> -        <a class="nav-link" href="installation.html">Installation</a>
Updated the installation link to be dynamic as it was failing in docs page if you got API reference page

2023-01-11 18:14 UTC, Mk996 commented on docs/source/_templates/home.html
> -                    <a href="installation.html" id="navbar-item" class="navbar-item is-secondary">
Good coding practice,
removed duplicate id attribute as that should be unique across elements

2023-01-11 18:15 UTC, Mk996 commented on docs/source/_templates/home.html
> -    <script src="_static/js/jquery.panelslider.min.js"></script>
removed few non-existing import, removing errors from the browser console

2023-01-19 17:39 UTC, skoudoro approved these changes
All good, thanks for this work @Mk996 , merging!

2023-01-19 17:39 UTC, merged