Update Peak actor shader
fury-gl/fury pull request #767
Opened 2023-03-20 17:04 UTC by skoudoro

in reference of #753, this is the refactoring of the Peaks actor shader to follow our new standard API.

2023-03-22 18:34 UTC, guaje requested changes
Hello @skoudoro. Thanks for taking the time to start standardizing the shader API. Here are some of my comments.

2023-03-22 18:34 UTC, guaje commented on fury/shaders/orient_to_rgb.glsl
>  vec3 orient2rgb(vec3 v)
This file should be in a folder determined by its function. Perhaps, `fury/shaders/utils`.

2023-03-22 18:34 UTC, guaje commented on fury/shaders/visible_cross_section.glsl
> +}
This file should be in a folder determined by its function. Perhaps, `fury/shaders/interaction`, but I'll leave the name up to you.

2023-03-22 18:34 UTC, guaje commented on fury/shaders/visible_range.glsl
> +}
This file should be in a folder determined by its function. Perhaps, `fury/shaders/interaction`, but I'll leave the name up to you.

2023-03-22 18:34 UTC, guaje commented on fury/actors/peak.py
> +
LGTM!

2023-03-23 19:39 UTC, skoudoro commented
Updated @guaje, Ready for a second review

2023-03-24 14:45 UTC, guaje commented
@skoudoro, thanks for this PR. LGTM, merging

2023-03-24 14:46 UTC, merged