Week 4 Blogpost
fury-gl/fury pull request #809
Opened 2023-06-26 21:09 UTC by JoaoDell

Hello guys, here is my week 4 blogpost:
![image](https://github.com/fury-gl/fury/assets/61475630/cb4eff51-1d0d-4256-b9d9-fdce6752bd75)

2023-06-27 14:06 UTC, ganimtron-10 requested changes
Hey @JoaoDell,
You blogpost generated well locally. I just had the below comments!

2023-06-27 14:06 UTC, ganimtron-10 commented on docs/source/posts/2023/2023-06-26-week-4-joaodellagli.rst
> +This Last Week's Effort
This sentence seem a bit odd to me.
You can either use `This Week's Effort` or `Last Week's Effort`.

2023-06-27 14:06 UTC, ganimtron-10 commented on docs/source/posts/2023/2023-06-26-week-4-joaodellagli.rst
> +experiment with simple shaders just as a a proof of concept that the FBO will be really useful for this project. I hope the road is less
`a` repeated twice in `just as a a proof`

2023-06-28 02:30 UTC, tvcastillod reviewed
Hi @JoaoDell, glad you were able to fix the problem, great teamwork!
I just have one minor comment, but everything else looks good to me.

2023-06-28 02:30 UTC, tvcastillod commented on docs/source/posts/2023/2023-06-26-week-4-joaodellagli.rst
> +   manager.window.SetOffScreenRendering(True) # so the window don't show up, but important for later as well
`don't` => `doesn't`

2023-06-28 15:57 UTC, JoaoDell commented
@ganimtron-10 @tvcastillod thanks for the reviews, just changed what you pointed out :)

2023-06-30 16:14 UTC, skoudoro approved these changes
Looks good to me, thanks to the reviewers and @JoaoDell.

small note for the future blog post: Try to do shorter sentences. Check general literature in english. Short sentences make it easier to read. The "last week effort" section is a bit hard read.  

Merging

2023-06-30 16:14 UTC, merged