GSoC: Adding Week 4 Blogpost
fury-gl/fury pull request #811
Opened 2023-06-27 17:05 UTC by ganimtron-10

![image](https://github.com/fury-gl/fury/assets/64432063/d15aca38-9f90-4bf6-b5c8-e518701e8808)

2023-06-28 03:00 UTC, tvcastillod reviewed
Hi, @ganimtron-10, it looks like it was a fruitful week despite being busy with exams, great job. The post was generated correctly, so everything looks good to me.

2023-06-28 17:40 UTC, JoaoDell requested changes
Well done Praneeth, I am amidst end-semester exams as well, so seeing you accomplish so many things while going through that is impressive, good luck with all of that! About your blogpost, everything seems fine, just one change I would do below

2023-06-28 17:40 UTC, JoaoDell commented on docs/source/posts/2023/2023-06-24-week-4-praneeth.rst
> +3. Independent Scrollbar Consideration: We are currently evaluating the necessity of making the Scrollbar an independent element. While currently, it is primarily used by the **ListBox2D**, we are ex
Here I would just take the comma: `While currently, it is primarily` -> `While currently it is primarily`

2023-06-29 15:27 UTC, ganimtron-10 commented
Thanks for the review @tvcastillod & @JoaoDell.

2023-06-30 16:18 UTC, skoudoro approved these changes
All good, Thanks to the reviewers and @ganimtron-10.

Merging

2023-06-30 16:18 UTC, merged