GSoC: Week 12 Blogpost
fury-gl/fury pull request #844
Opened 2023-08-23 23:31 UTC by JoaoDell

Hello everyone, here is my week 12 blogpost!
![image](https://github.com/fury-gl/fury/assets/61475630/5e7821bf-f8c1-4e85-bb59-031838e13531)

2023-08-25 14:42 UTC, ganimtron-10 requested changes
Hey @JoaoDell ,
I had these below comments. PTAL.

2023-08-25 14:42 UTC, ganimtron-10 commented on docs/source/posts/2023/2023-08-21-week-12-joaodellagli.rst
> +==========================
`=` symbol should cover the whole title

2023-08-25 14:42 UTC, ganimtron-10 commented on docs/source/posts/2023/2023-08-21-week-12-joaodellagli.rst
> +a way to control de intensities of the distributions.
`the` instead of `de`

2023-08-29 16:55 UTC, skoudoro approved these changes
All good, merging

2023-08-29 16:55 UTC, merged