ODF actor implemented with Ray Tracing
fury-gl/fury pull request #869
Opened 2024-03-08 16:25 UTC by tvcastillod

This PR aims to create a new odf actor defined with raymarching based on the paper _[Ray Tracing Spherical Harmonics Glyphs](https://www.willusher.io/publications/rt-sph-glyphs)_ . Work is still in progress.

2024-03-08 16:25 UTC, pep8speaks commented
Hello @tvcastillod, thank you for submitting the Pull Request!

* In the file [`docs/experimental/SH-ODF experimental/odf_example.py`](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py):

> [Line 14:38](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L14): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\e'
> [Line 14:51](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L14): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\S'
> [Line 14:71](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L14): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\c'
> [Line 14:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L14): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 23:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L23): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 24:5](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L24): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 27:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 28:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L28): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 29:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L29): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 30:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 31:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 32:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L32): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 33:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L33): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 34:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L34): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 35:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 36:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L36): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 37:80](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 41:12](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L41): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 42:5](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L42): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 44:70](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L44): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 47:21](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/docs/experimental/SH-ODF experimental/odf_example.py#L47): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`fury/actor.py`](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actor.py):

> [Line 3990:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actor.py#L3990): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 4001:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actor.py#L4001): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 4011:15](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actor.py#L4011): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'
> [Line 4020:29](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actor.py#L4020): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 4031:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actor.py#L4031): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`fury/actors/odf.py`](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py):

> [Line 15:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L15): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 34:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L34): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 37:60](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L37): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 39:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L39): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 78:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L78): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 80:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L80): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 95:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L95): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 96:1](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec7442c0c7b4408/fury/actors/odf.py#L96): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 97:5](https://github.com/fury-gl/fury/blob/d9c332340bb579e28f9c59706ec74 [...]

2024-03-22 00:27 UTC, guaje requested changes
Hi @tvcastillod, this new actor looks amazing!

I have added some comments to your PR. I'll keep adding comments to it.

2024-03-22 00:27 UTC, guaje commented on fury/actor.py
> +        raise ValueError('degree must be even')
`warnings.warn('Invalid degree value. Degree must be a positive even number lower or equal to 12. Ignoring passed value and using maximum degree supported by the number of SH coefficients.')`

2024-03-22 00:27 UTC, guaje commented on fury/actor.py
> +        degree = int((np.sqrt(8 * coeffs_given + 1) - 3)/2)
For comparison purposes this needs to be calculated anyway, so precalculate it before the `if` validations. The logic should be similar to this:

```python
max_degree = int((np.sqrt(8 * coeffs_given + 1) - 3) / 2)
if degree is None:
    degree = max_degree
else:
    if degree % 2 != 0:
        warnings.warn('Invalid degree value. Degree must be a positive even number ...')
        degree = max_degree
    else:
        coeffs_needed = ((degree + 1) * (degree + 2)) / 2
        if coeffs_given < coeffs_needed:
            warnings.warn('Not enough number of SH coefficients for degree {0}...')
            degree = max_degree
```

2024-09-05 22:11 UTC, guaje requested changes
Hello @tvcastillod, here are some minor comments on some of these files.

2024-09-05 22:11 UTC, guaje commented on fury/actors/odf.py
> +        //for (int i = 0; i != maxPolyDegreeVSOutput; ++i) {
Use the line with the uniform polynomial degree.

2024-09-05 22:11 UTC, guaje commented on fury/actors/odf.py
> +            float attenuation = ld.z;//dot(ld, normal);
Use `dot(ld, normal)`

2024-09-13 22:51 UTC, guaje requested changes
Hello @tvcastillod!

Overall great work putting up together such a needed actor.

In addition to the changes outlined below, I suggest moving the content of `rt_odfs` to `ray_tracing/odf`.

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +        float sqrt_discriminant = sqrt(discriminant);
Refactor using camel case convention (`sqrtDiscriminant`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +        float scaled_root = derivative[1] + ((derivative[1] > 0.0) ? sqrt_discriminant : (-sqrt_discriminant));
Refactor using camel case convention (`scaledRoot`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +        float root_0 = clamp(-2.0 * derivative[0] / scaled_root, begin, end);
Refactor using camel case convention (`root0`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +        float root_1 = clamp(-0.5 * scaled_root / derivative[2], begin, end);
Refactor using camel case convention (`root1`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +        float prev_derivative_order = float(maxPolyDegree + 1 - degree);
Refactor using camel case convention (`prevDerivativeOrder`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +        float begin_value = derivative[maxPolyDegree];
Refactor using camel case convention (`beginValue`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +            float current_begin = outRoots[i];
Refactor using camel case convention (`currentBegin`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/utils/find_roots.frag
> +            float current_end = outRoots[i + 1];
Refactor using camel case convention (`currentEnd`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/tournier/eval_sh_8.frag
> +void eval_sh_8(out float outSH[45], vec3 point)
Refactor using camel case convention (`evalSH8`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/tournier/eval_sh_6.frag
> +void eval_sh_6(out float outSH[28], vec3 point)
Refactor using camel case convention (`evalSH6`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/tournier/eval_sh_4.frag
> +void eval_sh_4(out float outSH[15], vec3 point)
Refactor using camel case convention (`evalSH4`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/tournier/eval_sh_2.frag
> +void eval_sh_2(out float outSH[6], vec3 point)
Refactor using camel case convention (`evalSH2`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/tournier/eval_sh_12.frag
> +void eval_sh_12(out float outSH[91], vec3 point)
Refactor using camel case convention (`evalSH12`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/tournier/eval_sh_10.frag
> +void eval_sh_10(out float outSH[66], vec3 point)
Refactor using camel case convention (`evalSH10`)

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/tonemap.frag
> +    float max_channel = max(max(1.0, linear.r), max(linear.g, linear.b));
Refactor using camel case convention (`maxChannel`)

2024-09-13 22:51 UTC, guaje commented on fury/actors/odf.py
> +    tonemap = import_fury_shader(os.path.join("rt_odfs", "tonemap.frag"))
Move to `lighting`

2024-09-13 22:51 UTC, guaje commented on fury/shaders/rt_odfs/eval_sh.frag
> +    }
Fix indentation and add an empty line at the end of the file

2024-09-24 12:52 UTC, skoudoro reviewed
exciting, thank you for this work @tvcastillod !

First, can you fix the issues from code format CI's and build doc CI's

then, see my first initial comments below.

Question: Can you explain a bit how did you get all this `eval_sh_*`?

2024-09-24 12:52 UTC, skoudoro commented on fury/actor.py
> +@warn_on_args_to_kwargs()
not needed since this is a new function

2024-09-24 12:52 UTC, skoudoro commented on fury/actor.py
> +    scales : float or ndarray (N, )
`, optional` to add

2024-09-24 12:52 UTC, skoudoro commented on fury/actor.py
> +    opacity : float
`, optional` to add

2024-09-24 12:52 UTC, skoudoro commented on fury/utils.py
> +    axis: int
`, optional` to add

2024-09-30 15:45 UTC, tvcastillod commented
> Question: Can you explain a bit how did you get all this `eval_sh_*`?

Hi @skoudoro,

The `eval_sh_*` are taken directly from the source code given in [the paper](https://www.willusher.io/publications/rt-sph-glyphs/) I took as reference, you can check their [shadertoy demo](https://www.shadertoy.com/view/dlGSDV) for a quick look. These values correspond to the SH basis functions listed in _Appendix A_ from the paper, which comes from the definition of Spherical Harmonics, the same from the [DIPY documentation](https://grgweb.luddy.indiana.edu/documentation/1.7.0/theory/sh_basis/). What I added was the Tournier basis which is very similar to Descoteaux with some sign changes.

2024-10-21 18:16 UTC, skoudoro commented
Hi @tvcastillod, 

Overall, it is almost ready to be merged. Can you fix Codespell CI's and Docs CI's which are failing...

In the docs CI, you have this 2 warnings:
```python
/home/runner/work/fury/fury/fury/actor.py:docstring of fury.actor.odf:16: WARNING: Inline literal start-string without end-string.
/home/runner/work/fury/fury/fury/actors/odf.py:docstring of fury.actors.odf.sh_odf:14: WARNING: Inline literal start-string without end-string.
```

Concerning the codespell, you need to add `shs` as an ignore word to avoid the issue. 


Thank you for the future update

2024-10-29 15:34 UTC, maharshi-gor commented
Hello @tvcastillod @guaje  @skoudoro 

Thanks for the work!

I tested this PR with a large dataset and when I tried to load the whole slice of that dataset. It worked perfectly fine. But if I zoom in it becomes distorted.
![unnamed](https://github.com/user-attachments/assets/698b0ff1-dc13-4ad2-b2ba-1a41c4084841)

**NOTE**

1. The current version of fury ODF Slicer Actor was smooth and better. I am only adding one slice of data to the proposed odf actor as well.
2. The current version of fury ODF Slicer Actor does not distort the image as well.

**My Observation and Take away**

- I think it is something related to zoom and the shapes are not getting recalculated once zoomed in more.
- We are doing something not right in the calculation implementation as it should be faster than the approach we have in fury.

Let me know if you need any information.

2024-10-30 12:44 UTC, guaje commented
> Hello @tvcastillod @guaje @skoudoro
> 
> Thanks for the work!
> 
> I tested this PR with a large dataset and when I tried to load the whole slice of that dataset. It worked perfectly fine. But if I zoom in it becomes distorted. ![unnamed](https://private-user-images.githubusercontent.com/39947025/381196484-698b0ff1-dc13-4ad2-b2ba-1a41c4084841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTIzOTQsIm5iZiI6MTczMDI5MjA5NCwicGF0aCI6Ii8zOTk0NzAyNS8zODExOTY0ODQtNjk4YjBmZjEtZGMxMy00YWQyLWIyYmEtMWE0MWM0MDg0ODQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEyNDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjRlYjU1NTE3NTA5NWIxODUwYWU0ZTQ2NGUxNmIzNmVlOGRjZDE0YjNkZGE4NWEzNzk5Y2UyZjc3MTA0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6yOQtaPzQGer_mSq182ExZqk4FudXXS9I0vKEMZl3Dw)
> 
> **NOTE**
> 
> 1. The current version of fury ODF Slicer Actor was smooth and better. I am only adding one slice of data to the proposed odf actor as well.
> 2. The current version of fury ODF Slicer Actor does not distort the image as well.
> 
> **My Observation and Take away**
> 
> * I think it is something related to zoom and the shapes are not getting recalculated once zoomed in more.
> * We are doing something not right in the calculation implementation as it should be faster than the approach we have in fury.
> 
> Let me know if you need any information.

Thanks for this thorough review @maharshi-gor. Could you share the dataset and detailed steps to generate the error?

2024-11-01 19:46 UTC, maharshi-gor commented
Hello @guaje @tvcastillod,

It is a dataset called setsompop. Please find the Dataset [here](https://indiana-my.sharepoint.com/:f:/g/personal/magor_iu_edu/Eiwiu6jfVYlLjYQVIUtl2hoBVA1Wuf4lD-cq1qMDTT3cBQ?e=Ogjqm2)

Please fit the entire slice using CsaOdfModel and then zoom it.

Also, I would love to see an example from your-side to use the new odf actor with a odf model as the inputs are different from the current odf slicer actor. This might be an input issue!

Thanks.

2024-11-08 18:30 UTC, maharshi-gor commented
Hey @skoudoro 

Let's merge this PR as for all the normal dataset it works fine. But for the large dataset @guaje and @tvcastillod are working on it.

I have created another issue to track that [here](https://github.com/fury-gl/fury/issues/943).

2024-11-08 19:01 UTC, skoudoro commented
Thank @maharshi-gor for the feedback, thanks @tvcastillod for this work and thanks @guaje for the review. merging

2024-11-08 19:01 UTC, merged